# Generated by Django 5.2.6 on 2025-09-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="login",
            name="cpf",
            field=models.CharField(default="00000000000", max_length=11),
        ),
        migrations.AddField(
            model_name="login",
            name="nome",
            field=models.CharField(default="Digite seu nome", max_length=100),
        ),
        migrations.AddField(
            model_name="login",
            name="rg",
            field=models.CharField(default="000000000", max_length=12),
        ),
        migrations.AddField(
            model_name="login",
            name="sobrenome",
            field=models.CharField(default="Digite seu sobrenome", max_length=100),
        ),
        migrations.AlterField(
            model_name="login",
            name="email",
            field=models.EmailField(
                default="Digite seu e-mail", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="login",
            name="senha",
            field=models.CharField(default="Digite sua senha"),
        ),
    ]
