# Generated by Django 5.2.6 on 2025-09-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0002_login_cpf_login_nome_login_rg_login_sobrenome_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Login",
            new_name="Cadastro",
        ),
    ]
