# Generated by Django 5.2.6 on 2025-09-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0003_rename_login_cadastro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastro",
            name="cpf",
            field=models.CharField(default="", max_length=11),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="email",
            field=models.EmailField(default="", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="nome",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="rg",
            field=models.CharField(default="", max_length=12),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="senha",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="sobrenome",
            field=models.CharField(default="", max_length=100),
        ),
    ]
